# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ccls-html_test"
  s.version = "0.3.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Marklund", "George 'Jake' Wendt"]
  s.date = "2013-06-27"
  s.description = "Ruby on Rails plugin for HTML validation and link checking"
  s.email = "github@jakewendt.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ccls-html_test.gemspec",
    "lib/DTD/xhtml-lat1.ent",
    "lib/DTD/xhtml-special.ent",
    "lib/DTD/xhtml-symbol.ent",
    "lib/DTD/xhtml.soc",
    "lib/DTD/xhtml1-frameset.dtd",
    "lib/DTD/xhtml1-strict.dtd",
    "lib/DTD/xhtml1-transitional.dtd",
    "lib/DTD/xhtml1.dcl",
    "lib/assertions.rb",
    "lib/ccls-html_test.rb",
    "lib/html_test.rb",
    "lib/link_validator.rb",
    "lib/url_checker.rb",
    "lib/url_selector.rb",
    "lib/validate_filter.rb",
    "lib/validator.rb",
    "rails/init.rb",
    "script/rails",
    "script/validate"
  ]
  s.homepage = "http://github.com/ccls/html_test"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Ruby on Rails plugin for HTML validation and link checking"
end

